Agoric/documentation

main/.vuepress/config.js
main/.vuepress/themeConfig/nav.js
main/smart-contracts-tutorials/guess37-multiple.md
main/smart-contracts-tutorials/guess37-one.md
main/zoe/guide/contracts/README.md

- Moves `/smart-contract-tutorials` into `/main`
- Renames `h1` in tutorials
- Fixes broken links
- Rearranges links for order

Arrange tutorials and add nav links

---

main/ertp/api/assay.md
main/ertp/api/mint.md
main/ertp/api/payment.md
main/ertp/api/purse.md

Updates examples so we don't have `mint.mint()` everywhere.
Add missing `mint.mint()` method in API. Added an explanation as to why the `.mint()` method creates a purse, which is a bit unintuitive at first.
Closes #36

Update mint.mint examples for clarity, add missing method

---

main/getting-started/README.md
package-lock.json
package.json

Modify the getting started instructions to use only the `agoric-sdk` version of `agoric-cli`.  We hope to make `npx agoric` also work in the future, but this has fewer dependencies and is more efficient.

Agoric CLI updates

---

main/getting-started/README.md

Refs: Agoric/agoric-sdk#634
The prerequisites section should appear in the overview, as it is confusing to jump to a different section when just trying to get things started.
Also, the link was broken.

Add the prerequisites to the Quick Overview

---

main/ertp/api/math-helpers.md
main/ertp/guide/math-helpers.md

Revised ERTP Guide section on MathHelpers and intro to ERTP API MathHelpers doc to explain in both places about the three types of MathHelpers, what and why to use them, and how to specify in code which type to use.

MathHelpers fix

---

main/getting-started/before-using-agoric.md
main/getting-started/start-a-project.md

Add a more focused clue on how to install the Agoric CLI.
The user already had to have `/usr/local/bin` in their `$PATH`, as this is the default configuration for fresh Linux/MacOS/Windows Subsystem for Linux setups.  Leverage that.

docs: fine-tune the link-cli instructions for novices

---

main/ertp/api/purse.md

Per comment from Kate on revised ERTP Guide, purse.getIssuer() shouldn't be in the API.

Remove purse.getIssuer command

---

main/zoe/guide/contracts/atomic-swap.md

Removed out of date Tip, changed last mod date to new day-month-year format used in the version date tag, tightened text.

Edit pass on Atomic Swap contract text 

---

main/zoe/guide/contracts/simple-exchange.md

Should 
{ give: { Asset: simoleans(5) }, want: { Price: quatloos(3) } }
{ give: { Price: quatloos(8) }, want: { Asset: simoleans(3) } }
use simoleansAmountMath.make(5) and similar instead? Or is this just the format of the order book?

Edit pass and date format update on Simple Exchange

---

main/zoe/api/zoe-contract-facet.md

Was using https://agoric.com/documentation/zoe/api/zoe-contract-facet when writing a smart contract and stumbled upon this small inconsistency.
Small fix.

Werent offerHandles retired an seats took their place?

---

main/.vuepress/config.js
package-lock.json
package.json

Links can be checked with `npm run check-links`, giving output below. Some may be false positives. Eventually, it would be nice to have this be part of CI before merging.

Add plugin to check internal links

---

main/.vuepress/config.js

Adds a link like this to the bottom of each page:
Which goes to an edit page like this:

chore: enable edit links on pages for easy PRs from external editors

---

main/zoe/api/zoe-contract-facet.md
main/zoe/api/zoe.md
snippets/test-intro-zoe.js
snippets/tools/fakeVatAdmin.js

Per Chris' request, updated docs to account for agoric-sdk changes in PR 1798. There are some questions that need answering for me to make the final small additions. See also [Agoric/agoric-sdk#1798](https://github.com/Agoric/agoric-sdk/pull/1798)

Update docs (with questions) for SDK PR Vat shutdown patch 1798

---

main/getting-started/start-a-project.md

Within a table made with html, it appears that we cannot use the normal markdown links. I think we need to create the tables with markdown as a long term fix.

fix: fix link.

---

package.json

Adds a `yarn build` script that merely does `exit 0` so that we can use the same scripts for testing all dapps + documentation

chore: add a yarn build for conformity with dapps

---

CONTRIBUTING.md
main/distributed-programming.md
package.json
snippets/test-distributed-programming.js

Several changes to the Notifier protocal are updated.
This version uses tested snippets for its examples, so the code should
stay more up-to-date.
The description pre-dates the write-up of async iterables and doesn't
mention that altenative.
closes: #352

docs: update documentation on Notifiers

---

main/README.md

Also redirected the links to the Intros to ERTP and Zoe instead of the much more overwhelming Guides to each.

Markdown links don't work when in HTML code. Fixed.

---

main/zoe/api/zoe.md

This changes the documentation to match the change in https://github.com/Agoric/agoric-sdk/pull/2116
#agoric-sdk-branch: 2113-zoe-installationP

chore: change type of installation in startInstance

---

main/zoe/guide/contracts/loan.md
snippets/zoe/contracts/test-loan.js

Update documentation to match changes in 2114-loan-period-notifier on agoric-sdk. 
Replaces `periodAsyncIterable` with `periodNotifier` in the terms.
#agoric-sdk-branch: 2114-loan-period-notifier

chore: update documentation to match changes in 2114-loan-period-notifier on agoric-sdk

---

main/zoe/guide/contracts/multipoolAutoswap.md

typo: `getOutputPrice()` was rendered as `getOutPutPrice()` in one place.
Submitted from the "Help us improve this page!" link. Is this an easier way to make tiny changes?

Fix typo multipoolAutoswap.md

---

main/getting-started/before-using-agoric.md

I ran into this issue when I setup the env several months ago and it happened again while I was helping a friend who is not versed in the JS-ecosystem. We both run Ubuntu 20.04 LTS.
Please let me know if you rather have an issue rather than a PR.

Addressed missing dependency

---

main/ertp/api/issuer.md
main/ertp/guide/issuers-and-mints.md

Closes out [#171](https://github.com/Agoric/documentation/issues/171) via notes in the relevant places warning not to create issuers in deploy scripts.

Issuer deploy script

---

CONTRIBUTING.md
main/.vuepress/config.js

This PR changes the themeConfig settings to show h3 by default. The individual settings for each sidebar item are unnecessary and are removed. CONTRIBUTING.md is updated.

chore: sidebar shows h3 by default

---

main/distributed-programming.md
main/ertp/api/amount-math.md
main/ertp/api/issuer.md
main/ertp/api/mint.md
main/ertp/api/payment.md
main/ertp/api/purse.md
main/ertp/guide/README.md
main/ertp/guide/amount-math.md
main/ertp/guide/amounts.md
main/getting-started/ertp-introduction.md
main/glossary/README.md
main/zoe/api/zoe-contract-facet.md
main/zoe/api/zoe-helpers.md
main/zoe/api/zoe.md
main/zoe/guide/contracts/covered-call.md
main/zoe/guide/contracts/fundedCallSpread.md
main/zoe/guide/contracts/pricedCallSpread.md
main/zoe/guide/price-authority.md
main/zoe/guide/proposal.md
snippets/ertp/guide/test-amount-math.js
snippets/ertp/guide/test-amounts.js
snippets/ertp/guide/test-issuers-and-mints.js
snippets/zoe/contracts/test-callSpread.js

This PR updates the documentation for agoric-sdk using Nat 4.0.0 (https://github.com/Agoric/agoric-sdk/pull/2475).
Things changed in https://github.com/Agoric/agoric-sdk/pull/2475:
* Nat values such as `moola3` are [BigInts](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt) rather than Numbers: `{ brand, value: 3n}` 
* Expiration dates and deadlines are also BigInts. E.g:
```
const myProposal = harden({
give: { Asset: quatloos(4)},
want: { Price: moola(15) },
exit: { afterDeadline: {
timer,
deadline: 100n,
}}
})
```
Still to do:
#agoric-sdk-branch: 325-nat-4.0.0-zoe

chore: update for Nat 4.0.0

---

main/zoe/api/zoe-contract-facet.md
main/zoe/api/zoe.md

Updates remaining allocation getters to note that post-exit they return the allocation values at exit.

Allocations

---

main/.vuepress/config.js
main/guides/js-programming/README.md
main/guides/js-programming/agoric-js-overview.md
main/guides/js-programming/eventual-send.md
main/guides/js-programming/ses/README.md

This cleans up the sidebars to reflect, as best as is possible, overall navigation when on a page, particularly SES and the other JavaScript related docs.
As I'm understanding the VuePress docs, there's a fundamental issue that sidebars are pretty tightly coupled with folder and file organization in the repo. While one can include a file in more than one sidebar, when that file is displayed, only the sidebar that matches its location in the doc repo file structure is shown. For example, while Documentation Guide appears in both the Getting Started and Guides sidebars, if you click on it in either one and display it, it will always show the Getting Started sidebar since the documentation-guide.md file is in the getting-started folder, and not the guides folder. We have issues because it's …

Sidebar patch 21 03 21

---

.github/workflows/build-deploy-doc.yml

This CI task deploys the built site from `main` via an SSH Github action to our web site.
Tested with this PR's branch, verified, and then removed the current PR's branch from CI.

Automatic deployment to web site

---

main/zoe/guide/contracts/README.md

Link was broken because there was an extra space. Removed space.

Fix broken link in Zoe Contracts

---

main/zoe/api/zoe-contract-facet.md

[Issue 494](https://github.com/Agoric/documentation/issues/494) described how to elaborate on how to correctly use ZCFSeat.exit() and .fail().

Fix for issue 494; elaborate on how ZCF.fail is used

---

main/guides/js-programming/agoric-js-overview.md
main/guides/js-programming/ses/lockdown.md
main/guides/js-programming/ses/ses-guide.md
main/guides/js-programming/ses/ses-reference.md
main/guides/wallet/README.md
main/guides/wallet/api.md
main/zoe/guide/contract-requirements.md

While going through the documentation, I found a few issues:
- A couple missing characters in  the JS programming overview
- Outdated links to the `SES-Shim` repo
- A few words out of place, possibly the result of copy paste
- The Wallet API has a `getDepositFacetId` instead of a `getDepositFacet` (possible introduced in #390)
Each of these changes are in separate commits.

Typo, copy and link fixes

---

main/guides/js-programming/agoric-js-overview.md
main/guides/js-programming/ses/ses-guide.md

- Dynamic import is now stage 4
- Make clear that dynamic `import` would bypass compartment shim because of its syntax status
- Microtask and task queuing nits
- Add Set and WeakSet as allowed globals for completeness
- Clarify why incomplete eval regex is safe

Updates to JS programming overview page

---

package.json
yarn.lock

This will allow Agoric SDK packages to begin migrating away from `node
-r esm`.

chore: Patch RESM for emigration

---

package.json

This adds a parsers declaration to package.json, which Endo's compartment mapper recognizes that a `.js` file is a JavaScript module and not a CommonJS module, but unlike `"type": "module"`, does not confuse `node -r esm`.

fix: Add language hint for Endo archive generator

---

main/zoe/api/zoe-helpers.md
main/zoe/guide/contract-requirements.md
package.json
snippets/contract-format.js
snippets/ertp/guide/test-amount-math.js
snippets/ertp/guide/test-amounts.js
snippets/ertp/guide/test-issuers-and-mints.js
snippets/ertp/guide/test-purses-and-payments.js
snippets/ertp/guide/test-readme.js
snippets/test-distributed-programming.js
snippets/test-intro-zoe.js
snippets/tools/setupZcfTest.js
snippets/tools/zcfTesterContract.js
snippets/zoe/contracts/test-callSpread.js
snippets/zoe/contracts/test-loan.js
snippets/zoe/contracts/test-oracle.js

This change changes all imports to use extensions in preparation for using ESM proper in Node.js.

refactor: Use import extensions

---

main/getting-started/intro-zoe.md
main/glossary/README.md

With the imminent change to bundle contracts as base64 encoded Zip files, this prepares the documentation so folks can extract the contract source for review.

docs: How to review a zipped up bundle

---

package.json

This ensures that bundleSource can find Zoe with the Endo Zip bundle format when that becomes the default.  For this case, I elected to keep the bundleSource example simple rather than thread the `dev` option.

fix: Move zoe to dependencies

---

snippets/ertp/guide/test-readme.js

The snippet `getId` does not make sense in the context of the ertp/guide/readme.md as it was.
Updated to be more sensible, plus it now hints at promise pipelining instead of having an unnescisarry `await` in it.
The sooner we get Agoric beginners to internalize promise pipelining the less `await`ing everything has to do.

Update test-readme.js snippet getId

---

main/zoe/guide/contracts/README.md
main/zoe/guide/contracts/constantProductAMM.md

Accompanies https://github.com/Agoric/agoric-sdk/pull/4006.  See also https://github.com/Agoric/agoric-sdk/issues/3862
This documents the current state of the constantProduct AMM, and adds in some discussion of how to interact with governance (Which is being added by the PR above).

Documentation for the constantProduct AMM

---

main/.vuepress/config.js
main/.vuepress/themeConfig/nav.js
main/README.md
main/getting-started/before-using-agoric.md
main/getting-started/start-a-project.md
main/guides/js-programming/README.md

- demote Documentation Guide - "how to read the documentation" should be implicit by following conventions; for now, just get it out of the way of folks getting started
- format installation instructions conventionally (fenced code rather than table)
- add quick-start
- integrate Nov 2020 video
- format "starting a project" steps conventionally
- integrate Nov 2020 video
trial deployment:
https://ag-docs-org.netlify.app/documentation/getting-started/before-using-agoric.html
https://ag-docs-org.netlify.app/documentation/getting-started/start-a-project.html#initialize-demo-from-dapp-template

optimize getting started path

---

main/guides/wallet/ui.md

They don't place nicely with the documentation site and aren't used in other pages

Remove links from section headers

---

.github/workflows/build-deploy-doc.yml

Publish the documentation site on the new staging site.
This is needed to prepare for our website migration.

ci(build-deploy-doc): temporarily build on `staging2` as well

---

main/zoe/api/zoe.md

The `getVatStats()` call was removed in #3337.

update doc for AdminFacet

---

.wordlist.txt
main/.vuepress/config.js
main/glossary/README.md
main/guides/README.md
main/guides/js-programming/ses/README.md
main/guides/js-programming/ses/lockdown.md
main/guides/js-programming/ses/ses-guide.md
main/guides/js-programming/ses/ses-reference.md
main/zoe/guide/contract-requirements.md

This change reviews every occurrence of SES in the documentation and either replaces it with Hardened JavaScript or Endo, or clarifies that it refers specifically to one of the three entities that retain the old name: the shim, the standard proposal, or the strategy group.
This change adds sections that call out Endo specifically in the glossary and its role in the Agoric programming environment.

docs: Generally straighten out SES and Endo references

---

main/getting-started/start-a-project.md

* clearer expectation around `agoric start` & `agoric start --reset`
* specify the link to the local wallet endpoint
* specify the link to wallet-ui documentation

docs: Clearer instructions for  getting-started/start-a-project

---

main/guides/js-programming/hardened-js.md

docs: fixed incorrect guide for setting up eslint to work with jessie

---

package.json
snippets/ertp/guide/test-amount-math.js
snippets/test-intro-zoe.js
snippets/zoe/contracts/test-callSpread.js
snippets/zoe/contracts/test-loan.js
snippets/zoe/contracts/test-oracle.js
yarn.lock

- refactor: Remove the now-superfluous babel-standalone
- chore: Update yarn.lock
I have run `yarn-deduplicate` here since there was certainly some nonsensical duplication of compatible semver range packages, but there remain some duplicates because of skew between the most recent Endo and Agoric SDK releases, that I assume will settle when an Agoric SDK release goes up with the latest Endo dependencies.
Refs https://github.com/Agoric/agoric-sdk/issues/4785

refactor: Remove now-superfluous babel-standalone

---

main/.vuepress/config.js

I think this makes the [Glossary](https://agoric.com/documentation/glossary/) more readable, and on other pages has a negligible effect.
Before | After
-- | --

style: Italicize in-page links

---

.github/workflows/build-deploy-doc.yml

This enables the deployment to succeed by avoiding making changes to `yarn.lock`.

ci(build-deploy-doc): ensure we don't modify yarn.lock

---

_redirects

Break the forwarding loop with a temporary redirect.

fix: forward to main site for errors

---

main/zoe/guide/contracts/treasury.md

https://github.com/Agoric/agoric-sdk/blob/4e0aece631d8310c7ab8ef3f46fad8981f64d208/packages/run-protocol/src/vaultFactory/vaultFactory.js#L216
> ```js
>   const publicFacet = Far('vaultFactory public facet', {
>     /** @deprecated use makeVaultInvitation instead */
>     makeLoanInvitation: makeVaultInvitation,
>     makeVaultInvitation,
> ```

chore: Replace references to deprecated method "makeLoanInvitation"

---

CONTRIBUTING.md
main/.vuepress/config.js
main/ertp/api/amount-math.md
main/getting-started/before-using-agoric.md
main/getting-started/start-a-project.md
main/guides/chainlink-integration.md
main/guides/js-programming/README.md
main/guides/js-programming/eventual-send.md
main/guides/js-programming/hardened-js.md
main/zoe/guide/contracts/atomic-swap.md
main/zoe/guide/contracts/automatic-refund.md
main/zoe/guide/contracts/autoswap.md
main/zoe/guide/contracts/barter-exchange.md
main/zoe/guide/contracts/constantProductAMM.md
main/zoe/guide/contracts/covered-call.md
main/zoe/guide/contracts/escrow-to-vote.md
main/zoe/guide/contracts/fundedCallSpread.md
main/zoe/guide/contracts/loan.md
main/zoe/guide/contracts/mint-and-sell-nfts.md
main/zoe/guide/contracts/mint-payments.md
main/zoe/guide/contracts/oracle.md
main/zoe/guide/contracts/otc-desk.md
main/zoe/guide/contracts/pricedCallSpread.md
main/zoe/guide/contracts/second-price-auction.md
main/zoe/guide/contracts/sell-items.md
main/zoe/guide/contracts/simple-exchange.md
main/zoe/guide/contracts/treasury.md
main/zoe/guide/contracts/use-obj-example.md

* Express full dates as "mmm d, yyyy" (strftime `%b %-d, %Y`), e.g. "Nov 5, 1955".
* Express months as "mmmm yyyy" (strftime `%B %Y`), e.g. "October 1985".
The styles were taken from existing content, but I'd be happy to change to any other unambiguous convention.

fix: Express dates uniformly and reference agoric-sdk contents by permalink

---

main/dapps/README.md
main/getting-started/deploying.md
main/getting-started/start-a-project.md

Mostly phrasing/style improvements. The most substantial change is removal of lines mentioning nonexistent `init` and `lib` directories in the (default) Dapp template.

fix: Cleanup the Dapp Guide

---

main/getting-started/before-using-agoric.md
main/getting-started/intro-zoe.md
main/glossary/README.md
main/zoe/api/zoe.md
main/zoe/guide/proposal.md

Mostly editorial changes to increase readability and internal consistency and addition of hyperlinks, but there are a few fixes of e.g. broken link targets and invalid code.
This is probably best reviewed using the rich diff, at least for a first pass.

fix: Clean up the glossary

---

main/ertp/api/brand.md
main/ertp/api/issuer.md
main/ertp/api/mint.md
main/ertp/api/payment.md
main/ertp/api/purse.md
main/ertp/guide/issuers-and-mints.md
main/ertp/guide/purses-and-payments.md
main/getting-started/ertp-introduction.md
main/glossary/README.md

Fixes #654
Also includes general consistency/cleanup of affected pages. Probably best reviewed commit-by-commit.

Restrict "burn" to describing operations that destroy assets

---

main/.vuepress/config.js

Reworked to move docs site to docs.agoric.com
once deployed, agoric.com/documentation/* will redirect to docs.agoric.com/:slug

fix: redirect root to docs

---

CONTRIBUTING.md
main/guides/js-programming/hardened-js.md
main/guides/zoe/contract-requirements.md
main/guides/zoe/contracts/atomic-swap.md
main/guides/zoe/contracts/automatic-refund.md
main/guides/zoe/contracts/barter-exchange.md
main/guides/zoe/contracts/constantProductAMM.md
main/guides/zoe/contracts/covered-call.md
main/guides/zoe/contracts/escrow-to-vote.md
main/guides/zoe/contracts/fundedCallSpread.md
main/guides/zoe/contracts/loan.md
main/guides/zoe/contracts/mint-and-sell-nfts.md
main/guides/zoe/contracts/mint-payments.md
main/guides/zoe/contracts/oracle.md
main/guides/zoe/contracts/otc-desk.md
main/guides/zoe/contracts/pricedCallSpread.md
main/guides/zoe/contracts/second-price-auction.md
main/guides/zoe/contracts/sell-items.md
main/guides/zoe/contracts/simple-exchange.md
main/guides/zoe/contracts/use-obj-example.md
main/guides/zoe/contracts/vault.md
main/guides/zoe/price-authority.md
main/reference/ertp-api/ertp-data-types.md
main/reference/repl/networking.md

At https://github.com/endojs/endo/pull/1469#discussion_r1089011161 @turadg explains advantages of docs urls using `master` rather than `HEAD`. Although he says "not worth another commit", the advantages seem compelling enough to be worth one.
Recommend reviewing with "Hide whitespace"
See https://github.com/endojs/endo/pull/1473

docs: rename HEAD to master in urls in md files

---

main/guides/zoe/actual-contracts/PSM.md

Phrase it in the ever-present tense to document the software component independent of how it may be deployed in a particular blockchain.

reword multiple PSMs re software component

---

package.json
snippets/ertp/guide/test-issuers-and-mints.js

Add in an `await` missing from a test case.
I think this missing `await` accounts for the error seen at https://github.com/Agoric/agoric-sdk/actions/runs/4329187639/jobs/7559543922 of PR https://github.com/Agoric/agoric-sdk/pull/7112

fix: missing await revealed by #7112

---

main/guides/getting-started/syncing-up.md

Add pismoC info plus retroactive instructions to build Cosmos layer and agd.

Update "syncing-up from mainnet" for pismoC

---

main/reference/zoe-api/zcfseat.md

Correct some details in `zcfSeat.fail()`,  and elaborate on the relations between `userSeats` and `zcfSeats`.

corrections to zcfSeat.fail; update kinds of seats

---

package.json

The docs repo must not be more strict than the SDK, otherwise the agoric-sdk "test-documentation" CI workflow fails.
Reverts/replaces one piece of 2835b382dfc3b73e3568627ebed78fe1a2cbc67d

package.json: set 'engines' to same value as SDK

---

snippets/ertp/guide/test-readme.js

Use `makeFakeBoard` in tests. Required for https://github.com/Agoric/agoric-sdk/pull/7636
```
#agoric-sdk-branch: mhofman/7578-no-fake-baggage
```

chore: use makeFakeBoard

---

main/reference/zoe-api/zoe-contract-facet.md

The description of setOfferFilter is not correct. It claims that it blocks the use of **keywords**, when in actuality, it blocks the use of some invitations.

Correct description of set/getOfferFilter

---

main/guides/js-programming/far.md
main/guides/js-programming/hardened-js.md

The counter example is not a smart contract. A smart contract in our framework is a module that exports a `start` or `prepare` function.
And "x is secure" is a claim that we typically don't make. Security is rarely an absolute property but more often a matter of degree.

fix: counter example heading/description

---

main/.vuepress/config.js
main/.vuepress/themeConfig/nav.js
main/guides/coreeval/README.md
main/guides/coreeval/local-testnet.md
main/guides/coreeval/permissions.md
main/guides/coreeval/proposal.md
main/guides/getting-started/README.md

Here's the initial pass at CoreEval documentation. 
BTW, some of the changes which originally appeared in this PR have been moved to the revisedgettingstarted PR (https://github.com/Agoric/documentation/pull/811).
The gist with the output from the initial set of console commands is located here: https://gist.github.com/Tyrosine22/6da2367ae8897736953c2f1286164eed
The gist with the output from the final set of console commands is located here:
https://gist.github.com/Tyrosine22/12ba3222f15926f25eee30ce86be33f2

Documentation for the CoreEval feature

---

main/reference/ertp-api/amount-math.md
main/reference/ertp-api/brand.md
main/reference/ertp-api/issuer.md
main/reference/ertp-api/mint.md
main/reference/ertp-api/payment.md
main/reference/ertp-api/purse.md
main/reference/zoe-api/README.md
main/reference/zoe-api/price-authority.md
main/reference/zoe-api/ratio-math.md
main/reference/zoe-api/user-seat.md
main/reference/zoe-api/zcfmint.md
main/reference/zoe-api/zcfseat.md
main/reference/zoe-api/zoe-contract-facet.md
main/reference/zoe-api/zoe-data-types.md
main/reference/zoe-api/zoe-helpers.md
main/reference/zoe-api/zoe.md

Contains the updates relevant to the atomicRearrange() update of the Zoe API. Also contains formatting changes to the method declarations to make them more legible. (This is why the various ERTP topics were touched.)
Note: i omitted mentioning the atomicTransfer() function entirely, as it seemed superfluous & thus needlessly confusing. If you feel strongly about this omission, bounce the PR back to me & I'll add it.

Deprecatedzoe

---

main/reference/zoe-api/zoe.md

This returns info that isn't specific to any zoe contract. It describes the feeIssuer, which is the issuer of **IST**.

correct zoe.getConfiguration()

---

main/reference/repl/networking.md

refs: Agoric/agoric-sdk#8127
We relaxed the "in the same block" restriction for acknowledgements a while ago.  Document it as such.

docs(network): remove mention of obsolete "need prompt ACK" for IBC

---

main/guides/js-programming/hardened-js.md
snippets/test-hardened-js.js

Newer SES `Date.now()` and `new Date()` throw exceptions starting with `secure mode`.
This updates the snippets tests to tolerate both the new behaviour, and for compatibility, the old behaviour of `Date.now()` returning `NaN`.

test(snippets): permit Date "secure mode" exceptions

---

main/README.md

- Always `JavaScript` and never `Javascript`
- `skill set` not `skillset`

Fix minor spelling issues on homepage

---

main/.vuepress/styles/index.styl
main/README.md

Make video embed link look better by being larger on desktop browser and still scale well on mobile devices.
The main trick here is to make sure everything is in a div with class="home-section" to be sure gutters/margins are good. 
Then ensure a fixed 16/9 aspect ratio for the video embed, a maximum height, and with those constraints, let it scale to fill its parent.
Also use slightly different iframe embed options to get rid of the youtube logo that was covering the DoraHacks logo.
preview link tested in chrome with all mobile devices in dev tools.

Improve video link aspect ratio

---

main/guides/getting-started/syncing-up.md

In agoric-upgrade-9 section:
Added:
`cd agoric-sdk`
After: 
`git clone https://github.com/agoric/agoric-sdk.git; agoric-sdk && git checkout tags/agoric-upgrade-9`

Added missing `cd` command

---

main/.vuepress/config.js
main/.vuepress/styles/index.styl

Router logic was swallowing history entries and not scrolling far enough for such targets[^1] to clear the fixed header.
[^1]: which do not currently exist but are being added, cf. https://github.com/Agoric/documentation/pull/876#discussion_r1409657230

feat: Improve the jump-to-fragment fixup for non-heading targets

---

main/.vuepress/config.js
main/guides/agoric-cli/agd-query-tx.md

rendered:
- [Using agd to make queries and transactions](https://dc-agd-query-tx.documentation-7tp.pages.dev/guides/agoric-cli/agd-query-tx.html) on `dc-agd-query-tx` branch

docs: Using agd to make queries and transactions

---

main/guides/subquery-indexing.md

There is a missing space between words in the recently published subquery docs from #873 
This adds the space

docs(subquery): fix typo, missing space

---

main/guides/js-programming/hardened-js.md

Very small nitpick, as this link redirect to youtube video at 1525-second mark and `1525 = 25*60 + 25`

Update timestamp with second too

---

main/guides/agoric-cli/README.md
main/guides/getting-started/README.md

also includes:
these last 2 changes can be removed if we want to postpone that step.

docs(agoric-cli): add agoric run; deprecate beta features

---

main/guides/getting-started/README.md

- note benign error messages
- 10x2 log messages seems excessive; 3 pairs establishes the pattern
- use block numbers closer to what they'll see

docs(getting-started): refine docker:logs section

---

main/guides/getting-started/README.md

The instruction to run `yarn start:ui` was the only yarn command not in a code block. This had it rendering with a different background than every other command a user should run. This standardizes it.

getting-started: make all commands user runs use codeblock

---

main/guides/getting-started/README.md

Considering wget is by default installed on most OSes. Let's use it and remove curl from the `Prerequisites`.

Remove curl from the prerequisites

---

main/guides/zoe/README.md

docs: tone down some Zoe claims

---

main/guides/getting-started/README.md

@kbennett2000 does this seem more useful or distracting?
- [rendered](https://dc-start-contract-steps.documentation-7tp.pages.dev/guides/getting-started/#starting-the-dapp-smart-contract)
Not urgent / important. But it's a blurb I wrote at one point and I'd like you to take a look before I discard it.

docs(getting-started): note major steps in `start:contract`

---

_redirects

I found the old URL being used at random places on the internet. Redirecting to new location.
Ref: https://v1.cosmos.network/tools

Redirect getting-started to new URL

---

main/.vuepress/config.js

remove from TOC:
- redundant offer safety explanations
- proposal (already covered)
- price authority (oddly placed?)
refs #918
or does it? thoughts, reviewers?

chore: demote zoe pages that need work

---

main/guides/integration/chain-integration.md

- (sort of) closes #864, which claims these links do not work

feat: make chain-integration > cosmos-sdk links clickable

---

main/guides/zoe/README.md

- Added link to E(zoe).startInstance under "Starting a Contract Instance" section

Updated to include link to Zoe API Docs

---

main/.vuepress/config.js
main/guides/zoe/contract-basics.md
main/guides/zoe/contract-upgrade.md
package.json
snippets/zoe/contracts/test-zoe-hello.js
snippets/zoe/src/02-state.js
snippets/zoe/src/02b-state-durable.js
yarn.lock

goal:
fixes #750
rendered:
- [Contract Upgrade](https://dc-durable-upgrade.documentation-7tp.pages.dev/guides/zoe/contract-upgrade.html)
Audience is dapp/contract devs, so the emphasis is on how to achieve it, not the theory of how the infrastructure works. @LuqiPan , @kbennett2000  I'm particularly interested to know if this brief account covers the subject well enough for you to get a working knowledge of it.
It lacks detail on interface guards. I propose to merge this as is and add those later. Opinions?
I started trying to make sure all the code snippets are really tested, but `makeZoeKitForTest` doesn't support upgrade, and it's not clear to me how to do bootstrap tests with `makeSwingsetTestKit` from outside agoric-sdk; I have already spent probably too much time on tooling in #965. …

contract upgrade

---

main/reference/zoe-api/zoe.md

- replaces #821 (branch exists on a personal remote)
> The exit behavior of an afterDeadline offer before the deadline occurs is not entirely clear in the documentation. The [current behavior](https://github.com/Agoric/agoric-sdk/blob/pismoD/packages/zoe/test/unitTests/zcf/test-zcf.js#L992-L994) is that it is in the waived state until the deadline occurs, but one could mistakenly think it is in the onDemand state until the deadline occurs without explicit mention.

feat(zoe): describe afterDeadline functionality in more detail

---

main/index.md

suggestions for #996
1. refine 1st row of feature boxes
2. replace repeated row with support contacts, based on an internal sketch

homepage suggestions

---

main/.vitepress/config.mjs
main/.vitepress/themeConfig/nav.js

Lots of material (/guides/wallet/ etc.) documents the ag-solo / mailbox architecture... the beta preview of our eventual permissionless contract deployment model, extending our Distributed Computing Framework to a stateful peer on end-user machines.
That material is a distraction to folks building for what's in production in the mainnet-1B VM.
So demote it from navigation menus, at least.
refs #973

chore: demote beta / pre-smart-wallet material

---

main/.vitepress/config.mjs

- see https://vitepress.dev/reference/default-theme-edit-link#edit-link for implementation details
- closes #1003

fix: edit this page links are missing

---

main/.vitepress/config.mjs
main/.vitepress/themeConfig/nav.js

In preparation for organizing navigation around Learn / Build, this is a minimally invasive navigation menu update for the current docs.
refs #973
closes #967
stacked on #1002
includes #1006

docs: navigation for a path thru current docs

---

main/guides/zoe/actual-contracts/index.md

The Dec 2022 date from the <Zoe-Version/> component is not relevant to the deployed contracts.

chore(actual-contracts): prune irrelevant Zoe-Version

---

main/guides/coreeval/permissions.md
main/guides/governance/index.md
main/guides/zoe/pub-to-storage.md
main/reference/vstorage-ref.md
main/reference/zoe-api/zoe-helpers.md

closes #947
please excuse incremental work toward...
- https://github.com/Agoric/documentation/issues/945
turning whitespace off in the diff should help.
subsumes:
- #1015

docs: vstorage reference; chainStorage publishing guide

---

main/guides/getting-started/index.md

What do you think?
rendered:
- https://dc-gs-video-up.documentation-7tp.pages.dev/guides/getting-started/

docs(getting-started): move embedded video to top

---

.github/workflows/test-build.yml
.github/workflows/test-snippets.yml

avoid:
error typescript-eslint@7.3.1: The engine "node" is incompatible with this module. Expected version "^18.18.0 || >=20.0.0". Got "18.17.1"

build(ci): relax node version constraint

---

main/.vitepress/config.mjs

I don't think we meant to take this out of the left nav bar (and "next page" links) in #1018 .

fix: restore Hardened JavaScript etc. to nav

---

main/.vitepress/config.mjs
main/reference/zoe-api/zoe-contract-facet.md
main/reference/zoe-api/zoe-helpers.md

follow-up to #951
drive-by: Make it easier to find ZCF APIs

prefer makeInvitation(..., proposalShape) to assertProposalShape

---

main/guides/getting-started/index.md

Fixes #1079
Also updates to canonical spelling and capitalization for [nvm](https://github.com/nvm-sh/nvm) and [Node.js](https://nodejs.org/).

docs(getting-started): Refer to nvm installation instructions

---

main/guides/getting-started/explainer-deploying-a-smart-contact.md
main/guides/getting-started/explainer-how-to-start-a-local-chain.md
main/guides/getting-started/index.md

I am changing documentation pages for the Getting Started dapp. Here is a summary:
1. The headings/steps on the index page look cluttered (a sentiment shared by multiple new devs), so I have numbered them as a first step.
2. After the `start-contract` command step, there is an explanation of what is happening under the hood. This seems unnecessary; therefore, I am hiding it in `<details>` tag. 
3. In the Keplr installation, there is a missing step regarding `selecting chains` (or rather not selecting them) that confuses some people, so I am adding it.
4. `print-key` has been removed from the code but there are still some references in the docs so I am removing them.

docs: GettingStarted Simplified

---

main/.vitepress/config.mjs
main/.vitepress/themeConfig/nav.js
main/guides/UIComponentLibrary/index.md

Content changes including adding Leap Elements, cleaning up page and linking Amount Input and Smart Wallet Provisioning

Update and rename UIComponentsstart.md to index.md

---

main/guides/zoe/contract-basics.md
snippets/zoe/contracts/test-zoe-01-hello.js

This pull request includes changes to the `contract-basics.md` file, which generates the documentation page titled `Smart Contract Basics`. Here's a summary of the modifications:
1. I have revised the language used in the section introducing the greetings smart contract. The wording is now more formal and easier to follow.
2. I've added additional text to the testing section of the contract basics to enhance readability.
3. I've removed extraneous code from the `test-zoe-hello.js` file, specifically code unrelated to the greetings smart contract. To maintain existing links and references, I've preserved the original file without alterations. Additionally, I've created a new file named `test-zoe-01-hello.js`, which will be used in the contract basics documentation.
4. The docs in the first …

Elaborate Contract Basics based on new developer experience

---

.github/workflows/test-getting-started.yml

Adding getting-started-test-pipeline.yml to the pipeline and ensure it runs as mentioned in the docs.
Will only run on `main` branch on [dapp-offer-up](https://github.com/Agoric/dapp-offer-up)
fixes #892

Add getting-started-test-pipeline.yml

---

main/.vitepress/config.mjs
main/guides/zoe/contract-access-control.md
main/guides/zoe/contract-basics.md
main/guides/zoe/contract-hello.md
main/guides/zoe/contract-state.md
snippets/zoe/src/02-state.js
snippets/zoe/src/03-access.js

I am using this PR to add structure to contract basics docs. Essentially, I am splitting the three smart contracts discussed there to their separate pages. I also added some introductory text to the original contract basics page and added text to the remaining pages for improved readability.

Revamping contract basics docs by splitting contracts and enhancing readability

---

main/e2e-testing.md

The PR updates the section related to arguments accepted by setupWallet`. 
This is being done because of an [issue](https://github.com/agoric-labs/synpress/issues/47) fixed by @frazarshad

docs: update setupWallet params in e2e testing docs

---

main/guides/agoric-cli/agd-query-tx.md

Add agd query vstorage keys reference mentioned in #1110

docs: Add agd query vstorage keys command reference

---

main/guides/getting-started/ui-tutorial/querying-vstorage.md

this page is missing a title because there is no h1

docs(vstorage): start headings at level 1

---

main/guides/agoric-cli/agd-query-tx.md
main/guides/coreeval/index.md
main/guides/coreeval/proposal.md
main/guides/integration/chain-integration.md
main/guides/zoe/contracts/otc-desk.md
main/reference/ertp-api/ertp-data-types.md
main/reference/zoe-api/zoe.md

Fixed a few broken links (not all) [here](https://github.com/Agoric/documentation/issues/1071).
1. Link to https://hub.cosmos.network/delegators/delegator-guide-cli.html is fixed on two pages.
2. ~Removed parts of text with outdated links in `chain-integration` docs. @dtribble Let me know if you want me to keep these parts and fix them with by linking something.~
3. Broken link fixed in coreeval/proposal.md
4. Removed probably a typo link in zoe.md. @gibson042 Please confirm that it was a typo.
5. Text `display-software` in ertp-data-types.md was linked to `ui-component` package which has been removed from repo - linked it to `ui-kit` repo now. 
6.Link to page "Cosmos Code with Us workshop" is broken as page was removed from cosmos website. I removed the link but kept the text.
This …

fix: broken internal links at multiple pages issue #1071

---

main/.vitepress/config.mjs
main/guides/orchestration/index.md

- Added an `orchestration` directory under `main/guides/` and created `index.md` file.
- Added orchestration overview and a code snippet - this will probably be updated very soon
rendered:
- [Orchestration Overview \| Agoric Documentation](https://ms-addding-orchestartion-ind.documentation-7tp.pages.dev/guides/orchestration/#orchestration-overview)
refs
- #930

Added orchestration overview and a code snippet

---

main/glossary/index.md
main/guides/orchestration/index.md

Added entries for 
- Baggage
- Exo
- Interchain Accounts (ICA)
- Orchestration
- Zones
to glossary. Most of the text added was pulled from corresponding readme files.

Adding Baggage-Exo-ICA-Orchestration-Zones to Glossary 

---

main/guides/coreeval/permissions.md

line below is similar to the line above

docs: typo in smart contract permission document

---

main/guides/getting-started/tutorial/index.md

the "your first dapp" link went to contract basics
and it opened in a new window because it was absolute. Links within the docs are relative.

fix tutorial index links

---

main/guides/ertp/issuers-and-mints.md
main/guides/ertp/purses-and-payments.md
main/reference/ertp-api/issuer.md
main/reference/ertp-api/payment.md

The PR marks `split()`, `combine()`, `claim()`, and `splitMany()` methods of an issuer object as deprecated in various sections of the documentation where they've been documented.  
Routes to verify:
- [Issuer](https://80bc127d.documentation-7tp.pages.dev/reference/ertp-api/issuer.html)
- [Payment](https://80bc127d.documentation-7tp.pages.dev/reference/ertp-api/payment.html)
- [Purses and Payments](https://80bc127d.documentation-7tp.pages.dev/guides/ertp/purses-and-payments.html)
- [Issuers and Mints](https://80bc127d.documentation-7tp.pages.dev/guides/ertp/issuers-and-mints.html)

docs: deprecate methods for issuer

---

main/glossary/index.md
main/guides/orchestration/getting-started/api.md
main/guides/orchestration/getting-started/key-concepts.md

This PR addresses the following:
- Fixes links in the ICA section of the documentation.
- Formats the document using Prettier, adds backticks where needed and highlights important information.
- Adds links to the relevant codebase and spec sections.
refs
- [Issue 1143](https://github.com/Agoric/documentation/issues/1143)
- [Issue 930](https://github.com/Agoric/documentation/issues/930)

Improvements in Orch Docs on Key Concepts Page

---

main/guides/orchestration/getting-started/api.md

The PR does the following:
- Add links referring to orchestration spec. 
- Formatting the files via Prettier
- Minor updates `OrchestrationAccount` explanation.  
refs
- [Issue 1143](https://github.com/Agoric/documentation/issues/1143)
- [Issue 930](https://github.com/Agoric/documentation/issues/930)

Improvements in Orch API docs

---

main/guides/orchestration/getting-started/contract-walkthrough/cross-chain-swap.md
main/guides/orchestration/getting-started/contract-walkthrough/cross-chain-unbond.md

There are similar changes for two of the walkthroughs in orchestration section: [Cross Chain Swap](https://docs.agoric.com/guides/orchestration/getting-started/contract-walkthrough/cross-chain-swap.html) and [Cross Chain Unbond](https://docs.agoric.com/guides/orchestration/getting-started/contract-walkthrough/cross-chain-unbond.html). The major change is use of the new `withOrchestration` API.
**Refs:**
- Issue #1154 
- Issue #1143

Update Orchestration Walkthrough

---

main/guides/agoric-cli/index.md

Add `follow` command reference to doc

docs: Add follow command to Agoric CLI Reference

---

main/glossary/index.md

Adding a glossary entry for smart contracts.
**ref(s):**
[https://papers.agoric.com/smart-contracts-encyclopedia-entry/](https://papers.agoric.com/smart-contracts-encyclopedia-entry/)
[https://github.com/Agoric/documentation/issues/62](https://github.com/Agoric/documentation/issues/62)
[https://github.com/Agoric/agoric-sdk/issues/244](https://github.com/Agoric/agoric-sdk/issues/244)

docs: adding smart contract entry to glossary

---

main/glossary/index.md

adding a3p definition into glossary. Assuming it should go first

adding a3p to glossary

---

main/guides/getting-started/index.md

Refs: https://github.com/Agoric/documentation/issues/1174
`Installing Yarn` section in getting started docs does not specify a version. We currently only support Yarn 1 and this PR updates the docs to explicitly specify that.

chore: specify yarn version in getting started

---

main/index.md

In discussion with Santi, I updated the docs homepage to be more consistent with the main message on the Agoric homepage.
screenshot:

docs: re-focus main page on orchestration

---

main/guides/getting-started/explainer-deploying-a-smart-contact.md
main/guides/getting-started/explainer-how-to-make-an-offer.md
main/guides/getting-started/explainer-how-to-start-a-local-chain.md
main/guides/getting-started/index.md
main/guides/getting-started/sell-concert-tickets-contract-explainer.md
main/guides/getting-started/swaparoo-how-to-swap-assets-explainer.md
main/guides/getting-started/swaparoo-making-a-payment-explainer.md
main/guides/js-programming/eventual-send.md
main/guides/js-programming/hardened-js.md
main/guides/js-programming/index.md
main/guides/zoe/index.md

Closes: https://github.com/Agoric/documentation/issues/1191
Multiple pages, along with [Zoe guides page](https://docs.agoric.com/guides/zoe/), don't render fully due to a hydration error. The problematic element was narrowed down to be the iframes being rendered on this page. Even though iframes are included in the server-side render, the content of it is only loaded on the client side. This results in a mismatch between SSR and CSR resulting in a hydration error. This PR fixes that by wrapping the corresponding `iframe`s in `ClientOnly` tag which ensures that they are only rendered on the client-side, preventing any mismatch.
| Before | After |
|------|----|
| https://docs.agoric.com/guides/getting-started/explainer-deploying-a-smart-contact | …

docs: fix hydration errors due to `iframe`s sitewide

---

main/reference/zoe-api/ratio-math.md

Closes: https://github.com/Agoric/documentation/issues/1183
Fixes Ratio Math page's rendering issues due to hydration. The root cause turned out to be how BigInts were being translated to html code when written in non-codeblock form. 
Also fixes some cases where there were no matching closes braces/parentheses.
**Before**
https://github.com/user-attachments/assets/41a41ccb-819b-4383-9df9-bb2199a5aa3f
**After**
https://github.com/user-attachments/assets/64e05ed3-17fa-49fb-8f15-20ac8a18d48f

fix: Ratio Math page partially rendering

---

.github/workflows/test-markdown.yml
main/guides/integration/chain-integration.md
main/guides/orchestration/how-orch-works.md

Fixes md formatting of a couple merged files and names the ci workflow so it can be marked required.

fix: md formatting 

---

main/guides/coreeval/permissions.md
main/guides/ertp/index.md
main/guides/ertp/purses-and-payments.md
main/guides/getting-started/contract-rpc.md
main/guides/getting-started/explainer-how-to-make-an-offer.md
main/guides/getting-started/sell-concert-tickets-contract-explainer.md
main/guides/getting-started/ui-tutorial/agoric-provider.md
main/guides/getting-started/ui-tutorial/connect-wallet.md
main/guides/getting-started/ui-tutorial/making-an-offer.md
main/guides/getting-started/ui-tutorial/querying-vstorage.md
main/guides/js-programming/notifiers.md
main/guides/zoe/actual-contracts/index.md
main/guides/zoe/contract-upgrade.md
main/reference/repl/board.md
main/reference/repl/priceAuthority.md
main/reference/vstorage-ref.md

Mostly simplify internal links in docs. Clean, for example, `../../..` type links.

Clean Internal Links

---

main/guides/coreeval/index.md
main/guides/coreeval/proposal.md

Contract Installation link in https://docs.agoric.com/guides/coreeval/proposal.html
points to: 
https://docs.agoric.com/guides/zoe/#contract-installation
There is no discussion about contract installation on that page. It seems that intended page with the 
relevant section is: https://docs.agoric.com/guides/zoe/contract-walkthru.html
I am fixing the link.

fix: bad link in core-eval proposal section

---

main/.vitepress/config.mjs
main/guides/orchestration/how-orch-works.md

Mainly expanding ICA description based on Dan's comments.

Updating Page: How-Does-Orchestration-Work

---

package.json
scripts/markdown-js-snippets-linter.mjs
yarn.lock

The issue arose because we introduced `glob` as a dependency in https://github.com/Agoric/documentation/pull/1212
The version introduced in this repo doesn't mesh well with the version(s) being used in some of the packages in agoric-sdk and hence, the linking step failed. Once I aligned the CI check breakage with the changes in docs repo, it was easier to pinpoint the root cause. 
As a fix, I have downgraded `glob` to the version that works for both cases. CI check now passes on agoric-sdk with this branch: https://github.com/Agoric/agoric-sdk/actions/runs/11157393879/job/31011590384?pr=10206

chore: downgrade glob

---

main/.vitepress/config.mjs
main/.vitepress/themeConfig/nav.js
main/guides/orchestration/getting-started/contract-walkthrough/send-anywhere.md
main/guides/orchestration/getting-started/contract-walkthroughs.md

`send-anywhere` Orchestration Contract Walkthrough docs are added.
Refs:
- https://github.com/Agoric/documentation/issues/1179
- https://github.com/Agoric/documentation/issues/1143

Adding `send-anywhere` Orchestration Contract Walkthrough

---

main/guides/orchestration/getting-started/contract-walkthrough/cross-chain-unbond.md

`unbond` example contract in `orchestration` has changed since we lasted documented it here. This is an update based on the new changes.
Refs:
- https://github.com/Agoric/documentation/issues/1179
- https://github.com/Agoric/documentation/issues/1143

Update Orch/Unbond Walkthrough

---

main/.vitepress/themeConfig/nav.js
main/guides/orchestration/index.md

updated the entrypoint guide landing page for orchestration docs from internal feedback.

Orchestration landing page doc update for launch

---

main/guides/zoe/contract-upgrade.md

- `Far` link does not point to `Far` page instead points to `zone`.
- `InterfaceGuard` link is a palceholder that somehow slipped into `main`.

Fixing a couple of links in Contact Upgrade page

---

main/guides/js-programming/hardened-js.md
main/guides/zoe/contract-access-control.md

The PR introduces the concepts of "widely shared" and "closely held" resources under the Principle of Least Authority (POLA) section.

docs: closely held vs widely held

---

main/.vitepress/config.mjs
main/guides/zoe/contract-details.md
main/guides/zoe/contract-upgrade.md
main/reference/zoe-api/zoe.md
snippets/zoe/src/02b-state-durable.js

closes: #1126
Collect the details on creating durable contracts in one place. Update to cover use of `meta`  with `start` and stop recommending `prepare` for this.
Also provide some cross-linking between various descriptions of the approach.

Durable contracts

---

main/guides/getting-started/contract-rpc.md

[Building Client Dapps page](http://localhost:5173/guides/getting-started/contract-rpc.html) is updated to contain a box with a summary of [the discussion related to public readonly contract state query](https://github.com/Agoric/agoric-sdk/discussions/10372).

Adding a Box Describing VStorage as readonly Contract State Query

---

main/reference/zoe-api/zoe.md

I included a test for `getProposalShapeForInvitation()` in a more general test for invitation guards, and discovered that the docs were incorrect. This corrects them.

docs: update parameter type for getProposalShapeForInvitation()

---

package.json
scripts/format.mjs
scripts/markdown-js-snippets-linter.mjs

In an effort to address visibility issues regarding what command to run to fix lint errors, this PR highlights the usage of `yarn format` on encountering lint errors. [Relevant thread](https://agoricopco.slack.com/archives/C03G190GBHP/p1733339480648079).

lint: highlight `yarn format` usage on errors

---

package.json
scripts/checkLinks.mjs
scripts/format.mjs
scripts/markdown-js-snippets-linter.mjs

Closes: https://github.com/Agoric/documentation/issues/1225
Added this check to build script to keep it consistent with vitepress's built-in deadlink checker for md files (raises error during build time)
Unrelated but also formats the scripts dir.
Testing:
You can test by checking out the branch and entering invalid links.

chore: add a deadlink checker for nav/sidebar items

---

main/reference/zoe-api/user-seat.md

Issue [8610](https://github.com/Agoric/agoric-sdk/issues/8610) pointed out that `E(zoeSeat).getPayout('foo');` returned undefined when the keyword was unknown, while the types claimed that it always returned a Payment. 
[10738](https://github.com/Agoric/agoric-sdk/issues/10738) changed Zoe to throw if the Payment didn't exist. This PR updates the documentation to mention that error.

docs: getPayout() throws if there's no payment for the keyword

---

package.json
snippets/test-intro-zoe.js
snippets/tools/setupZcfTest.js
snippets/zoe/contracts/test-callSpread.js
snippets/zoe/contracts/test-loan.js
snippets/zoe/contracts/test-oracle.js
yarn.lock

Trying to fix [failing integration test in agoric-sdk](https://github.com/Agoric/agoric-sdk/actions/runs/13314133661/job/37184597814):
```
Link step
➤ YN0071: │ Cannot link @agoric/cosmic-swingset into @agoric/documentation@workspace:. dependency import-meta-resolve@npm:4.1.0 conflicts with parent dependency import-meta-resolve@npm:2.2.2
➤ YN0071: │ Cannot link @agoric/solo into @agoric/documentation@workspace:. dependency import-meta-resolve@npm:4.1.0 conflicts with parent dependency import-meta-resolve@npm:2.2.2
➤ YN0071: │ Cannot link @agoric/vats into @agoric/documentation@workspace:. dependency import-meta-resolve@npm:4.1.0 conflicts with parent dependency import-meta-resolve@npm:2.2.2
```

bump import-meta-resolve

---

main/guides/zoe/offer-safety.md

Offer-Safety means At least/at most
