Agoric/documentation

README.md
=> First shot at intention and outline for simplest smart contract tutorial

main/README.md
=> Fix front page Zoe link

main/ertp/api/payment.md, main/ertp/api/purse.md, main/ertp/guide/README.md, main/ertp/guide/contract-hosts.md, main/ertp/guide/default-configuration.md, main/ertp/guide/extent.md, main/ertp/guide/label.md, main/ertp/guide/mint.md, main/ertp/guide/unit-ops.md, main/ertp/guide/units.md
I reviewed all of guide and api pages
I fixed a couple things. I made one commit per file i made changes to so it's easy-ish to cherry-pick if some parts are not wanted
=> Other ertp doc changes

main/.vuepress/config.js, main/zoe/guide/contracts/covered-call.md, main/zoe/guide/contracts/simple-exchange.md
Add docs for two more contracts on Zoe, the coveredCall and the simpleExchange.
=> Add more Zoe contract docs

CONTRIBUTING.md, README.md
Move planning docs to "Contributing.md"
=> Fix front page if people wrongly get directed here. 

main/.vuepress/components/Zoe-Version.vue, main/.vuepress/config.js, main/.vuepress/styles/index.styl, main/zoe/api/README.md, main/zoe/api/structs.md, main/zoe/api/zoe-contract-facet.md, main/zoe/api/zoe.md, main/zoe/guide/README.md, main/zoe/guide/contracts/atomic-swap.md, main/zoe/guide/contracts/autoswap.md, main/zoe/guide/contracts/covered-call.md, main/zoe/guide/contracts/public-auction.md, main/zoe/guide/contracts/simple-exchange.md, main/zoe/guide/offer-rules.md, main/zoe/guide/offer-safety.md, main/zoe/roadmap/README.md
This PR adds a Vue component to display the current Zoe version and the last update date for all Zoe documentation pages.
=> Add "Zoe Version" component

main/.vuepress/themeConfig/nav.js
This PR updates the navigation for the move to the monorepo.
=> Update nav for monorepo

main/ertp/guide/create-fungible-erights.md, main/ertp/guide/create-non-fungible-tokens.md
Cherry picking @DavidBruant 's PR #83
=> Update non-fungible & fungible guides

main/getting-started/README.md
Minor details to help with initialising the `agoric` CLI.
=> Update the Getting Started for new agoric workflow

main/ertp/api/issuer.md, main/ertp/api/purse.md
and other clean-ups and clarifications
https://github.com/Agoric/documentation/issues/91
=> docs: update ERTP API doc to reflect the treatment of promises

.github/workflows/build-deploy-doc.yml
=> First attempt at adding deploy automation

main/getting-started/README.md, main/zoe/api/records.md, main/zoe/api/zoe-contract-facet.md, main/zoe/api/zoe.md
There still a few operations missing like `getCurrentAllocation`
=> Correct api docs for functions that are already there

main/getting-started/README.md, main/zoe/api/records.md, main/zoe/api/zoe-contract-facet.md, main/zoe/api/zoe-helpers.md, main/zoe/api/zoe.md, main/zoe/guide/README.md
docs: Add E references and fix up helpers.
=> More API docs improvements

main/.vuepress/themeConfig/nav.js, main/getting-started/README.md
docs: guide menu and better hackathon announce
=> doc menu improvement

main/.vuepress/config.js, main/zoe/guide/contract-requirements.md
=> First draft of contract requirements

main/.vuepress/themeConfig/nav.js, main/getting-started/before-using-agoric.md, main/getting-started/ertp-introduction.md, main/getting-started/start-a-project.md
I'm adding things as they come
If you think it's important to merge right now, feel free to merge
I'll merge myself soon anyway
=> Getting started 04 20

main/.vuepress/themeConfig/nav.js, main/distributed-programming.md, main/glossary/README.md
The text is really not perfect
but given the timeframe, i would recommand merging if this is considered better than the current nothing
I'm asking for a review specifically to have a different look and be sure it's actually better than nothing (make sure nothing is false or misleading) 
Closes #130
=> First draft about distributed programming with Agoric

main/zoe/guide/contracts/atomic-swap.md, main/zoe/guide/contracts/autoswap.md, main/zoe/guide/contracts/covered-call.md, main/zoe/guide/contracts/second-price-auction.md, main/zoe/guide/contracts/simple-exchange.md
=> Adds links to contract code and contract folder.

main/getting-started/agoric-cli-guide.md
=> Remove agoric start --no-restart option

main/distributed-programming.md
better descriptions of SES and programming with E.
=> Docs: Improved description of our programming environment

main/getting-started/development-cycle.md
Restored "agoric start --reset" step.
=> Fix development-cycle.md

main/zoe/api/README.md, main/zoe/api/zoe-contract-facet.md, main/zoe/guide/contracts/README.md
=> Add intros and descriptions to Zoe indexes

main/getting-started/README.md, main/getting-started/deploying.md
=> Doc patch 18 05 20

main/glossary/README.md
Revised and added ERTP topics to Glossary
=> Glossary patch june 2020

main/getting-started/deploying.md
See Documentation issue 205 (https://github.com/Agoric/documentation/issues/205)
=> Revised deploy descriptions for clarity

main/getting-started/README.md
Agoric is a company; Agoric SDK is the software product documented here.
"smart contract project" might refer to solidity etc.
=> use "Agoric SDK" more consistently

main/dapps/alpha-release-candidate.md
Address PR comments about https://github.com/Agoric/documentation/pull/244
=> Address comments about alpha release candidate updates

main/.vuepress/themeConfig/nav.js, main/getting-started/agoric-cli-guide.md, main/getting-started/before-using-agoric.md, main/zoe/api/zoe-contract-facet.md, package-lock.json, package.json
remove tags that were preventing rendering properly, update vuepress, other fixes
Closes #252
=> fix: remove tags that were preventing rendering properly

main/getting-started/ertp-introduction.md
This PR is for https://agoric.com/documentation/getting-started/ertp-introduction.html i.e. the ERTP Introduction under Getting Started in the docs. It updates the content for the Zoe Alpha Release. Following it will be PRs to update the ERTP API docs, and to completely revise and update the ERTP Guide.
=> Alpha release ertp introduction

main/zoe/api/zoe-helpers.md
=> Update documentation for changes to assertProposalShape

main/zoe/api/zoe-helpers.md
=> fix: update trade and swap documentation

main/ertp/api/payment.md, main/ertp/api/purse.md
Coordinate with https://github.com/Agoric/agoric-sdk/pull/1685
=> docs: update makeDepositFacet to getDepositFacet.

main/glossary/README.md
Checking the updated Glossary and realized this needed doing.
=> Removed MathHelpers and references

main/zoe/guide/offer-safety.md
This was all straightforward and basic conceptual. Did have one question
about what exitRule's default value is.
=> Tightened and clarified prose, fixed link

main/zoe/guide/contracts/covered-call.md
update the description of the coveredCall contract and the link to the source.
=> docs: update the description of the coveredCall contract.

main/zoe/guide/contracts/README.md, main/zoe/guide/contracts/atomic-swap.md, main/zoe/guide/contracts/second-price-auction.md
minor fix to atomicSwap description.
=> docs: update secondPrice auction description and link

main/zoe/guide/contracts/README.md, main/zoe/guide/contracts/barter-exchange.md
And add link for barter to README.
=> docs: update barter link

main/.vuepress/config.js, main/zoe/guide/contracts/README.md, main/zoe/guide/contracts/barter-exchange.md
=> docs: add barter exchange to sidebar

main/getting-started/alpha.md
Includes automatic white space removal, so compare with whitespace turned off.
=> chore: fix non/fungible token description

main/.vuepress/config.js
chore: turn on setting that adds last updated to all files, based on git data for that file
=> chore: turn on setting that adds last updated to all files

main/.vuepress/styles/index.styl, main/README.md
This PR makes some minor improvements to the front page. The CSS for the buttons on the frontpage is made the same as the other main button.
=>  chore: minor improvements to the front page

package-lock.json
=> chore: run npm install, npm audit fix

.github/workflows/test-build.yml
Adds a github workflow for testing the build on PRs
=> chore: add workflow for testing the build on PRs

.github/workflows/test-build.yml, main/.vuepress/components/Button-Action-Link.vue, main/getting-started/before-using-agoric.md, main/getting-started/development-cycle.md, main/getting-started/intro-zoe.md, main/getting-started/start-a-project.md
The following errors were found and fixed. This PR should help with runtime errors that aren't caught by the build process.
Note: I experimented with introducing a made-up tag with no closing tag and it did not catch that particular one. https://github.com/Agoric/documentation/pull/307
```
['"file:/github/workspace/main/.vuepress/dist/index.html":174.45-174.95: error: The element "button" must not appear as a descendant of the "a" element.',
'"file:/github/workspace/main/.vuepress/dist/index.html":177.44-177.94: error: The element "button" must not appear as a descendant of the "a" element.',
'"file:/github/workspace/main/.vuepress/dist/getting-started/development-cycle.html":166.2645-166.2662: error: The "border" attribute on the "table" element is obsolete. Use CSS instead.', …
```
=> chore: add html5 validator to CI

.github/workflows/test-build.yml, .github/workflows/test-snippets.yml, .gitignore, .pyspelling.yml, .wordlist.txt, CONTRIBUTING.md, main/getting-started/intro-zoe.md, package.json, snippets/contract-format.js, snippets/test-intro-zoe.js, snippets/tools/fakeVatAdmin.js, yarn.lock
This PR rewrites and updates the Zoe introduction. More product information is provided, and only necessary details are included.
This PR also adds the ability to import snippets of code and test them. 
Closes #310
=> chore: rewrite the Zoe introduction

main/ertp/guide/README.md, main/ertp/guide/amount-math.md, main/ertp/guide/amounts.md, main/ertp/guide/issuers-and-mints.md, main/ertp/guide/purses-and-payments.md, package.json, snippets/ertp/guide/test-amount-math.js, snippets/ertp/guide/test-amounts.js, snippets/ertp/guide/test-issuers-and-mints.js, snippets/ertp/guide/test-purses-and-payments.js, snippets/ertp/guide/test-readme.js, snippets/test-intro-zoe.js, snippets/tools/setupZcfTest.js, snippets/tools/zcfTesterContract.js, yarn.lock
This PR tests the code snippets in the ERTP guide. A number of small fixes were found - nothing alarming, but I think it's a good thing we are testing.
Closes #336
=> refactor: move snippets from ertp/guide

main/zoe/api/zoe-helpers.md
Added documentation for the new ZoeHelpers.
=> Zoe helpers 10 12 20

.wordlist.txt, main/dapps/README.md, main/dapps/dapp-templates.md, main/getting-started/agoric-cli-guide.md, main/getting-started/deploying.md, main/getting-started/start-a-project.md, main/wallet-api.md
Add list of dapp templates. Change default to fungible faucet.
See https://github.com/Agoric/agoric-sdk/pull/1883 for the related change in the default setting
=> chore: Add list of dapp templates. Change default to fungible faucet.

main/dapps/dapp-templates.md
I realized we had left out a few dapps in the earlier version.
=> chore: add mention of more dapps

main/getting-started/intro-hackathon.md
- Rewritten version of Documentation Guide. Note that due to being on a Chromebook, I'm not able to test it locally after VuePress processing.
=> How to get started with Agoric for Hackathon devs

main/.vuepress/config.js, main/zoe/guide/contracts/README.md, main/zoe/guide/contracts/oracle.md, package.json, snippets/test-intro-zoe.js, snippets/zoe/contracts/test-oracle.js, yarn.lock
Add documentation of the oracle contract
Closes https://github.com/Agoric/documentation/issues/374
=> chore: add oracle documentation

main/dapps/README.md, main/getting-started/README.md, main/getting-started/before-using-agoric.md, main/getting-started/start-a-project.md
=> docs: fix minor factual problems

main/getting-started/agoric-cli-guide.md, main/getting-started/start-a-project.md, main/zoe/guide/price-authority.md
This PR adds the declaration of `makeQuoteNotifier`, which replaces the older `getQuoteNotifier`, which replaced the older `getPriceNotifier`.
Also, a few updates to the `agoric-cli` guide.
=> docs: some updates for PriceAuthority

main/.vuepress/config.js, main/.vuepress/themeConfig/nav.js, main/zoe/guide/contracts/README.md, main/zoe/guide/contracts/loan.md
This PR adds a file for explaining the loan contract.
=> chore: add loan explanation

main/zoe/guide/contracts/loan.md, snippets/zoe/contracts/test-loan.js
This PR adds code snippets to the loan explanation
Closes #377 
Closes #384
=> chore: add code snippets to loan explanation

.github/workflows/test-snippets.yml, main/chainlink-integration.md, main/zoe/guide/contracts/oracle.md
Closes #379
Closes Agoric/dapp-oracle#9
=> docs: add chainlink-integration guide

main/zoe/guide/contracts/oracle.md
@katelynsills please let me know if this is clear enough for your question in https://github.com/Agoric/documentation/pull/388#discussion_r525408495
=> docs: describe the need for high-level oracle contracts

main/README.md
=> fix: use <a> inside html on front page

main/wallet-api.md
Overall update in progress, just getting rid of these now to close out the offerHandle doc issue #329
=> Removed defunct offerHandle methods to fix offerHandle issue.

main/platform/README.md
=> Made SwingSet spelling uniform.

main/ertp/api/purse.md
Will edit Guide after this is approved.
=> Added getAllegedBrand() and getCurrentAmountNotifier()

main/.vuepress/config.js, main/.vuepress/styles/index.styl, main/.vuepress/themeConfig/nav.js
Removes Hackathon from the URL.
Could not find a vuepress setting to change the mobile burger width to fix the navigation bug. Added CSS instead.
=> Navigation fix

snippets/zoe/contracts/test-loan.js
#agoric-sdk-branch: percentMath
=> test: update to tests to match percentMath PR in agoric-sdk

main/zoe/guide/contracts/loan.md, snippets/zoe/contracts/test-loan.js
see-also: https://github.com/Agoric/agoric-sdk/pull/2144
#agoric-sdk-branch: 2108-LoanUseNotifier
=> test: update loan test to use a Notifier

CONTRIBUTING.md, main/.vuepress/config.js
Updated Zoe version number and docs update date, checked that docs reflect changes since the version currently on there.
=> Version number

package.json, snippets/ertp/guide/test-amount-math.js, snippets/ertp/guide/test-purses-and-payments.js, yarn.lock
@michaelfig, I believe this should fix any issues you were seeing in https://github.com/Agoric/agoric-sdk/pull/2441#issuecomment-780113461. 
This does not work under Node 15, but I believe our CI doesn't use that yet.
=> chore: fix tests. Works under Node 14

main/getting-started/before-using-agoric.md, main/getting-started/start-a-project.md
Issues [432](https://github.com/Agoric/documentation/issues/432) and [435](https://github.com/Agoric/documentation/issues/435)
=> Cli cleanup 2021 02 16: Cleaned up minor install issues 

yarn.lock
I believe this fixes the [Node 15 issues](https://github.com/Agoric/agoric-sdk/issues/2454) we've been seeing.
=> chore: update the lockfile

snippets/zoe/contracts/test-loan.js
#agoric-sdk-branch: useRatios
https://github.com/Agoric/agoric-sdk/pull/2536
=> Upgrade for use of Ratios in Loan

CONTRIBUTING.md, main/.vuepress/config.js, main/dapps/README.md, main/distributed-programming.md, main/getting-started/agoric-cli-guide.md, main/wallet-api.md
@tyg, I think this should take care of #426 if you use these methods for any other pages that need sidebars. I'll let you take this PR from here.
=> chore: show two ways of adding config to show a sidebar

snippets/ertp/guide/test-amount-math.js
chore: fix the error message so it matches agoric-sdk https://github.com/Agoric/agoric-sdk/pull/2561
=> chore: fix the error message so it matches agoric-sdk

snippets/ertp/guide/test-amount-math.js, snippets/ertp/guide/test-amounts.js, snippets/ertp/guide/test-issuers-and-mints.js, snippets/ertp/guide/test-purses-and-payments.js, snippets/ertp/guide/test-readme.js, snippets/test-distributed-programming.js, snippets/test-intro-zoe.js, snippets/zoe/contracts/test-callSpread.js, snippets/zoe/contracts/test-loan.js, snippets/zoe/contracts/test-oracle.js
1830-ERTP-virtual-objects-payments
=> chore: prepare-test-env

snippets/zoe/contracts/test-callSpread.js, snippets/zoe/contracts/test-loan.js
#agoric-sdk-branch: 2600-new-amount-math-zoe
=> refactor: use new amountMath

main/zoe/api/contract-support/price-authority.md, main/zoe/api/contract-support/ratio-math.md, main/zoe/guide/contracts/atomic-swap.md, main/zoe/guide/contracts/covered-call.md, main/zoe/guide/contracts/mint-and-sell-nfts.md, main/zoe/guide/contracts/multipoolAutoswap.md, main/zoe/guide/contracts/second-price-auction.md, main/zoe/guide/contracts/simple-exchange.md, snippets/ertp/guide/test-amount-math.js, snippets/ertp/guide/test-amounts.js, snippets/ertp/guide/test-issuers-and-mints.js, snippets/ertp/guide/test-purses-and-payments.js, snippets/ertp/guide/test-readme.js, snippets/test-intro-zoe.js, snippets/zoe/contracts/test-loan.js
=> chore: some fixes to the amount math changes

package.json, snippets/ertp/guide/test-readme.js, yarn.lock
Refs: Agoric/agoric-sdk#2956 and Agoric/agoric-sdk#2945
#agoric-sdk-branch: mfig-2945-separate-ag-solo
=> Refactor @agoric/cosmic-swingset to @agoric/vats

main/guides/js-programming/README.md, main/guides/js-programming/far.md
Please note this is written for external developers and as much as possible covers how and when they should use far(). It does not go into detail about how far() and Remotables interact with presences and promises and the like, as it does not appear to me external devs need to know in depth what we're doing with Remotables "on the other side" as it were. If you think external devs do need to know this sort of in depth implementation, please let me know in comments. Thanks.
=> Far() documentation

main/.vuepress/config.js
Need to add Far to the js-programming sidebar menu
=> Added Far to js-programming sidebar

snippets/test-intro-zoe.js, snippets/tools/setupZcfTest.js, snippets/zoe/contracts/test-loan.js, snippets/zoe/contracts/test-oracle.js
#agoric-sdk-branch: move-fake-vat-admin
=> chore: move fakeVatAdmin

main/glossary/README.md, main/zoe/api/zoe-helpers.md
@tyg, I finally figured out what I want to call assertUsesNatMath :)
=> chore: make some more changes to AssetKind branch

snippets/ertp/guide/test-amount-math.js, snippets/ertp/guide/test-amounts.js, snippets/ertp/guide/test-issuers-and-mints.js, snippets/ertp/guide/test-purses-and-payments.js, snippets/ertp/guide/test-readme.js, snippets/test-intro-zoe.js, snippets/zoe/contracts/test-callSpread.js, snippets/zoe/contracts/test-loan.js, snippets/zoe/contracts/test-oracle.js
The CI on agoric-sdk was breaking due to a change in error message. This PR fixes the error message in one of the snippets tests, so that CI will pass. While I was changing that, I saw that amountMath had not been capitalized in the snippets, so I fixed that too.
=> chore: update documentation snippets for ERTP refactoring

snippets/contract-format.js
=> chore: remove reference to trade

main/zoe/guide/contracts/multipoolAutoswap.md, snippets/test-intro-zoe.js, snippets/tools/setupZcfTest.js, snippets/zoe/contracts/test-callSpread.js, snippets/zoe/contracts/test-loan.js, snippets/zoe/contracts/test-oracle.js
#agoric-sdk-branch: 3692-metering-clean-up
=> chore: update for Zoe metering

main/zoe/guide/contracts/README.md, main/zoe/guide/contracts/treasury.md
=> contract documentation for Treasury

main/.vuepress/config.js, main/README.md, main/getting-started/intro-zoe.md, main/glossary/README.md, main/guides/js-programming/agoric-js-overview.md, main/zoe/api/README.md, main/zoe/api/fees-and-metering.md, main/zoe/api/zoe-contract-facet.md, main/zoe/api/zoe.md, main/zoe/guide/README.md, main/zoe/guide/contract-requirements.md, main/zoe/guide/proposal.md, snippets/contract-format.js
This PR documents:
* privateArgs
* offerArgs
* getInstallationForInstance
* Fees, fee purses, invitation fees, and metering
Closes #551
=> chore: document changes to Zoe

main/.vuepress/config.js
This PR updates the Zoe version that shows on our documentation site. (the date that will show has been updated to 9/13/2021).
=> chore: update zoe version

main/dapps/dapp-templates.md, main/getting-started/deploying.md, main/guides/wallet/README.md
closes #532 (the wiki page no longer exists)
=> chore: remove dapp-encouragement mentions

main/repl/timerServices.md
Refs Agoric/agoric-sdk#3853
As described.
=> docs(timerServices): update for latest changes to agoric-sdk

main/zoe/api/contract-support/ratio-math.md
=> Update documentation on ratios to include floor and ceil operations

snippets/ertp/guide/test-amount-math.js, snippets/ertp/guide/test-issuers-and-mints.js, snippets/ertp/guide/test-readme.js, snippets/zoe/contracts/test-callSpread.js
Changes for https://github.com/Agoric/agoric-sdk/pull/3892
=> chore: update to match input validation changes

main/zoe/guide/contracts/treasury.md
ref: https://github.com/Agoric/agoric-sdk/pull/4026
=> Update Treasury doc for extracted AMM

main/zoe/guide/contracts/pricedCallSpread.md
somehow `s` got appended onto the end but seems all good now 👍
=> fixed broken link to pricedCallSpread.js contract

snippets/ertp/guide/test-purses-and-payments.js
See https://github.com/Agoric/agoric-sdk/runs/4631060065?check_suite_focus=true
=> Cope with upcoming version skew

snippets/ertp/guide/test-purses-and-payments.js
Forgot to escape these in previous PR
=> Escape brackets in regexp

package.json, yarn.lock
As @michaelfig [pointed out](https://github.com/Agoric/documentation/issues/610#issuecomment-1016961708), the documentation site documents the beta SDK.
=> chore: source deps from agoric beta

main/zoe/guide/contracts/treasury.md
Document https://github.com/Agoric/agoric-sdk/issues/4176
=> docs: InitialMargin gone

main/ertp/guide/README.md, main/getting-started/intro-zoe.md, main/platform/README.md
Ref 4d5b14a9f81c628b5597ed5f05208a5025de0d80
=> style: Unitalicize page-outbound links

main/ertp/guide/README.md
Ref 4d5b14a9f81c628b5597ed5f05208a5025de0d80
Ref a4f6b92c1183aebdf166813043b69f74bf004fda
=> style: Unitalicize outbound links

main/repl/networking.md
Synchronize with https://github.com/Agoric/agoric-sdk/blob/HEAD/packages/SwingSet/docs/networking.md (after https://github.com/Agoric/agoric-sdk/pull/4949 )
=> chore: Synchronize public networking docs with agoric-sdk

main/dapps/README.md, main/dapps/dapp-templates.md
refs: https://github.com/Agoric/agoric-sdk/issues/5037
Also removed some of the templates from the documentation because they are no longer maintained
=> chore: update dapp instructions

main/.vuepress/config.js, main/ertp/api/brand.md, main/ertp/api/payment.md, main/ertp/api/purse.md, main/ertp/guide/README.md, main/ertp/guide/amount-math.md, main/ertp/guide/amounts.md, main/ertp/guide/issuers-and-mints.md, main/ertp/guide/purses-and-payments.md, main/glossary/README.md, snippets/ertp/guide/test-issuers-and-mints.js
Follows up #655 and other recent "cleanup" PRs.
=> style: Cleanup ERTP Guide

main/getting-started/intro-zoe.md
One text blob was missing the new disclaimer test - this fixes it.
=> fix: patch last remaining text

main/getting-started/intro-zoe.md, main/zoe/api/fees-and-metering.md, main/zoe/api/zoe-contract-facet.md, main/zoe/guide/README.md, main/zoe/guide/contracts/README.md, main/zoe/guide/contracts/constantProductAMM.md, main/zoe/guide/contracts/treasury.md
=> chore: rename RUN to IST

snippets/ertp/guide/test-purses-and-payments.js
Adjust error message to work with https://github.com/Agoric/agoric-sdk/pull/5947
=> fix: adjust error message

main/README.md
changed top HERO button and cleaned up some text/links
=> Homepage revision

main/getting-started/beta.md
clean up for ["Start Coding" link ](https://github.com/Agoric/documentation/issues/705) issue @tgrecojs
=> embedded link to get started

main/getting-started/start-a-project.md
brought together some steps for terminal 1 and put some things in order a little better
=> shell consolidate

_redirects, package.json
This branch contains the redirect fixes that you made to the other branch... but without all the other changes that was in that branch, which aren't ready for prime time yet.
=> Fixing the redirect problem... for real this time.

snippets/test-intro-zoe.js, snippets/tools/setupZcfTest.js, snippets/zoe/contracts/test-loan.js, snippets/zoe/contracts/test-oracle.js
This change is backwards compatible.
=> chore: integrate with changes for Zoe durability

main/.vuepress/config.js, main/.vuepress/themeConfig/nav.js, main/guides/getting-started/syncing-up.md
Migrates syncing up docs into docs - where they should be!
=> fix: add syncing information

snippets/test-intro-zoe.js, snippets/zoe/contracts/test-callSpread.js
Upgrade in light of https://github.com/Agoric/agoric-sdk/pull/7080
in order to fix failing dapp test in https://github.com/Agoric/agoric-sdk/pull/7067
See https://github.com/Agoric/dapp-otc/pull/49
=> fix: use stratified customDetails

main/guides/wallet/README.md
https://www.w3.org/WAI/tips/writing/#make-link-text-meaningful
=> wallet guide: avoid _here_ links

main/guides/dapps/starting-multiuser-dapps.md, main/guides/wallet/ui.md
These references are stale, they are now `agd` and https://wallet.agoric.app/locator/
=> fix(solo): remove stale `ag-cosmos-helper` and `local.agoric.app` refs

main/guides/getting-started/README.md
Contains new setup info required by CoreEval, as well as a version update required by everything.
=> Revisedgettingstarted

main/guides/js-programming/README.md
This PR is a continuation of the old PR #796
=> Fixing broken image

main/reference/zoe-api/user-seat.md
see: https://github.com/Agoric/agoric-sdk/issues/8016
closes: #824
All the methods on userSeat are described as returning Promises, but some resolve immediately, while others can wait varying periods. This adds some clarity on what to expect.
=> Add timing details for userSeat promise returns

main/.vuepress/config.js
=> feat: Explain, DRY out, and isolate page fixups

main/README.md
Update homepage text based on convo with @rowgraus
=> update text with guidance from Rowland

main/guides/getting-started/start-a-project.md
Let devs know that this ag-solo / mailbox style is not how mainnet dapps work.
TODO:
- ~~link to permissioned deployment?~~
_editorial tweaks moved to separate PRs_
=> Start Project: beta ag-solo dapp architecture notice

main/guides/getting-started/README.md
Rearrange the wording for OSes
=> Rearrange the wording for OSes

main/.vuepress/themeConfig/nav.js, main/guides/getting-started/syncing-up.md
rendered:
- [Syncing Up on Mainnet](https://dc-prune-syncing.documentation-7tp.pages.dev/guides/getting-started/syncing-up.html)
fixes #792
cc @kbennett2000 , JD
=> chore(syncing-up): prune down to community forum links

main/guides/getting-started/README.md
- Changed title to "Getting Started"
- Added section to formally introduce the Dapp
- Embedded Video Walkthrough
=> Updated Getting Started docs

main/.vuepress/config.js
Per @sufyaankhan's request -- https://agoricopco.slack.com/archives/C0658HX317U/p1705606732042049?thread_ts=1705601527.204229&cid=C0658HX317U
=> config.js edit to remove link to Getting Started --> Syncing Up on Mainnet

main/guides/getting-started/README.md
Added summary section covering takeaways for the reader from this exercise
=> Added summary section at the end

main/reference/ertp-api/amount-math.md, main/reference/ertp-api/ertp-data-types.md
#916 is in @gibson042 's fork, which our ci bots don't seem to like.
=> chore: Miscellaneous improvements to ERTP API pages

main/guides/getting-started/index.md
@kbennett2000  would you please verify?
cf. https://github.com/Agoric/agoric-sdk/pull/8829#pullrequestreview-1931725530
=> feat(getting-started): --dapp-template no longer needed

main/.vitepress/config.mjs, main/.vitepress/themeConfig/nav.js, main/index.md, main/what-is-agoric.md
@sufyaankhan ,
@kbennett2000 and I played around with [the nav sketch in miro](https://miro.com/app/board/uXjVNpwnZ-I=/) . This is as far as we got.
goal:
fixes #973
stacked on a rebase of
- #996
=> doc: learn / build navigation

main/.vitepress/config.mjs, main/.vitepress/themeConfig/nav.js, main/guides/getting-started/contract-rpc.md
result of discussion with @sufyaankhan , @kbennett2000 , @LuqiPan 
was stacked on
- #1026
=> docs: build / learn nav with dapp-offer-up flow

main/guides/js-programming/eventual-send.md, main/guides/zoe/contract-basics.md
=> docs: $DEBUG, $LOCKDOWN_OPTIONS, $TRACK_TURNS

main/guides/getting-started/index.md
refs https://github.com/Agoric/agoric-3-proposals/issues/5
@kbennett2000 I'd like you to test this thoroughly in a bit. The ink is still drying just now...
cc @turadg
=> docs: used fixed key for keplr set-up

main/guides/getting-started/index.md
Changed node version from LTS to v18.18.0 to be compatible with dapp-agoric-basics
=> Changed node version from LTS to v18.18.0

main/guides/getting-started/index.md
* docs(getting-started): Use consistent grammatical aspect and mood for headings
* Remove extraneous whitespace
* Remove extraneous content
=> docs(getting-started): Miscellaneous cleanup

main/guides/UIComponentLibrary/UIComponentsstart.md
Fixed the test build pipeline issue introduced in this [PR](https://github.com/Agoric/documentation/pull/1077)
=> fix: Remove tag error in test pipeline

main/guides/getting-started/index.md
Numberings to headings in the getting started page were accidentally introduced by #1082 - I am removing them here.
=> docs: Removed the numberings to headings

.github/workflows/cf-logs-fetcher.yml
https://github.com/agoric-labs/cf-logs-fetcher/pull/1
Using the latest from https://github.com/marketplace/actions/cloudflare-log-fetcher
The latest version of this action will start working after we merge this PR.
=> Update cf-logs-fetcher.yml to latest version

main/guides/getting-started/ui-tutorial/agoric-provider.md, main/guides/getting-started/ui-tutorial/connect-wallet.md, main/guides/getting-started/ui-tutorial/querying-vstorage.md
I'll update each branch in https://github.com/agoric-labs/ui-tutorial as soon as this goes in, I have the commits ready to go
=> chore: update ui-kit versions in ui tutorial

main/guides/getting-started/index.md
Add instructions to run agoric app on macOS
=> docs: Add macOS settings to getting started

main/.vitepress/themeConfig/nav.js
I couldn't find the UI Tutorial the 1st time I looked for it.
=> docs: include UI tutorial in nav menu

main/guides/zoe/contract-basics.md
=> fix: fix the typo in contract-basics.md

main/index.md
Fix the wrong landing page links
=> fix: fix the landing page links

main/.vitepress/config.mjs, main/.vitepress/themeConfig/nav.js, main/guides/getting-started/tutorial/index.md
=> docs: add index page for tutorials

main/.vitepress/theme/style.css, main/index.md, package.json, yarn.lock
Update vitepress to the latest version and fix a style regression by moving local css variable overrides to `styles.css`
=> chore: update vitepress

main/guides/orchestration/getting-started/key-concepts.md
Mixing `await` style with `.then` and `.catch` is sufficiently confusing to novice JS programmers.  Please take advantage of `try-catch` instead.
=> doc(orch): use `try-catch`, not `.then` and `.catch`

main/guides/getting-started/index.md
Adding brief clarity on the following commands:
```
corepack enable
yarn --version # for verification
```
How's this @ivanlei ?
=> Update index.md with brief on yarn installation.

main/index.md
Based on today's hackathon debrief, the worked examples in dapp-offer-up and dapp-agoric-basics were key learning materials.
- [rendered](https://8b203704.documentation-7tp.pages.dev/)
screenshot:
=> feature example apps code on homepage

main/index.md
=> docs: orch. message more for builders

main/guides/orchestration/how-orch-works.md
In current proposed outline of orchestration docs [link for slack thread](https://agoricopco.slack.com/archives/C03UF6JMWE7/p1726038031437689), there is a page where details of IBC, ICA and other not-so-very-urgently-necessary information is to be shared. This PR creates first version of this page with the goal of incremental additions and improvements. WIP is not linked but here is the rendered markdown:
[How Orchestration Works](https://github.com/Agoric/documentation/blob/f920af26fc5c7a3f18334611a32c1de376cb7c11/main/guides/orchestration/how-orch-works.md)
=> docs: adding page: How Orchestration Works

main/guides/getting-started/contract-rpc.md
=> doc: update link and image of vstorage-viewer

.github/workflows/test-getting-started.yml
This PR (finally) makes the CI for this repo all _green_ 🚀
=> ci: fix getting-started check

package.json, yarn.lock
Bump Yarn 4.4 to [4.5](https://github.com/yarnpkg/berry/releases/tag/%40yarnpkg%2Fcli%2F4.5.0), trying to solve https://github.com/Agoric/agoric-sdk/actions/runs/11113362849/job/30880208649?pr=10175
Also bumped a bunch of deps in semver-compatible ranges using `yarn upgrade-interactive`
=> bump yarn and other deps

main/index.md
Closes: https://github.com/Agoric/documentation/issues/1229
=> chore: update Build card on main page

main/.vitepress/config.mjs
=> Fix Heading Links Behavior Inconsistency in Sidebar

yarn.lock
https://github.com/endojs/endo/releases/tag/ses%401.10.0
=> chore: Update Endo versions
